### PR TITLE
plugin: add functools.partial support to help

### PR DESCRIPTION
**Pull request by keur**

### CODE REVIEW

**Comment by abizer** [comment]
honestly I would simplify the widetext plugin and remove the 2 using partials entirely rather than doing this but it's fine I guess

**Comment by jvperrin** [comment]
So only having the single spaced option essentially?

**Comment by abizer** [comment]
yeah. the naming on those triggers is pretty awkward/long to remember and use as well

**Comment by jvperrin** [comment]
That's fair, I do agree it'll be hard to remember them.

I do think functools.partial support is a different issue though that would still be useful to support.

**Comment by keur** [comment]
@abizer if you want to change the triggers just push it straight to master. Fine by me.

**Comment by keur** [comment]
I say simplify the triggers, leave the partials, and add this?

**Comment by abizer** [comment]
yeah go for it

**Pull request merged**
