### PR TITLE
Remove spongebob

### PR DESCRIPTION
**Pull request by ethanhs**
The spongebob meme is objectionable for several reasons:
1. It is ableist. See https://twitter.com/A_Silent_Child/status/1132533156286992384, https://twitter.com/A_Silent_Child/status/1132529686775566336, and https://web.archive.org/web/20180815063154/http://www.bohemianpaladin.me/2017/05/20/ableism-and-spongebob/ discuss this further.
2. It can be insulting. The whole point is to mock someone...

IMO the first point alone is enough reason to remove it.

(Since the author of the first two tweets deleted their account, here are some of the linked tweets)
https://twitter.com/silverswansong/status/1067745332107362304
https://twitter.com/soul_into_hades/status/862517894755823617

### CODE REVIEW

**Comment by ethanhs** [comment]
@yvbbrjdr You have not cited any evidence that `!spongebob` is not ableist. In addition, I am mainly interested in focusing on removing `!spongebob` due to its ableism. If you would like to remove other items I suggest you open a new pull request and articulate why.

No whataboutism, please.

**Comment by yvbbrjdr** [comment]
My thoughts were "just because someone on the internet claims themself to be disabled and subjectively claims this to be ableist doesn't make it definitely ableist" since it's so subjective. But IANAL. We might need to consult a lawyer for the definite conclusion.

**Comment by ethanhs** [comment]
@yvbbrjdr thank you for your comment! (Reposting what I dm'd you for everyone else)

The reason why spongebob is ableist is due to the meaning of the alternating capitalization as a means of textually representing the speech of someone who is mentally differently-abled. Furthermore, the image associated with this text derives its humor from laughing at people with disfigurement.

**Comment by MCer4294967296** [comment]
https://us.battle.net/forums/en/overwatch/topic/20759232135

just popped off my head.

**Comment by dkess** [comment]
I personally don't use the spongebob command very much, so I have little stake in this. But supposed "ablism" is a bad reason to remove it. That argument is unconvincing-- no one intends to offend differently-abled people, nor have I seen evidence that it ever has been used for this purpose. As others have explained, it's simply a playful mocking tone.

The Twitter argument (and others) comes across as bandwagon outrage that isn't actually based in reality.

**Comment by yvbbrjdr** [comment]
+1 for that. I don't use this plugin much, but I hate seeing people forbid other people from doing certain things with an invalid reason. That's also my attitude towards the Great Firewall.

Also, given what is said in this thread, anonymously quote, "no one used this macro to mock disabled people. Thinking this is ablelist is ableist".

**Comment by cg505** [comment]
> That argument is unconvincing-- no one intends to offend differently-abled people, nor have I seen evidence that it ever has been used for this purpose. As others have explained, it's simply a playful mocking tone.

> No one at the OCF has used this to mock disabled people.

These quotes are indisputably true. However, it's still reasonable to arrive at the same conclusion as @ethanhs. For something as insignificant as an ircbot command, it is better to avoid potential association with ableism.

So for me, the argument that the meme is ableist does hold weight. But regardless of whether you agree, the fact that some people (especially disabled people!) think so is enough that I'd be glad to see it go.

> I'm not particularly attached to the plugin but the way in which it is going does concern me.

I agree here as well. We should not be pushing to master any feature change or other non-urgent or major change. Opening a PR, and posting to a few IRC channels "hey turns out this has ableist connotations, yikes. here's the PR to remove it" is the better approach, and should have been followed the first time, not the second. (I will say "unilaterally impose your will" might be stronger wording than I would use for changing an ircbot plugin.)

> If we are to set a precedent of taking this kind of reasoning seriously spongebob will be the first of many things to go.

If we are actually committed to becoming a more inclusive and diverse organization this may be true. It is not necessarily a bad thing. For major changes plenty of discussion is surely warranted. I don't consider this a major change.

**Comment by yvbbrjdr** [comment]
@cg505 

> But regardless of whether you agree, the fact that some people (especially disabled people!) think so is enough that I'd be glad to see it go.

I feel that the ircbot itself is an ableist. I feel so incompetent and offended seeing it modifying the database. I don't have the ability to do so by my hand. Please delete the bot as a whole.

**Comment by redplanks** [comment]
Regardless of your position on this, keep discussion reasonable. Clearly hyperbolic arguments like this don't help anyone.

**Comment by keur** [comment]
@redplanks 

> Clearly hyperbolic arguments like this don't help anyone.

It's actually not hyperbolic at all when the purported Twitter experts on the topic are using this [exact](https://twitter.com/soul_into_hades/status/862517894755823617) [style](https://twitter.com/tommyinboots/status/1125983092215357440) of [argumentation](https://twitter.com/a_silent_child/status/1132680207503155200)

**Comment by ethanhs** [comment]
@keur You seem to not understand several things. Let me start at the beginning:

1) I did not make this change unilaterally. This issue was brought to me by another OCF staff member. I consulted with php and nessa, who happened to be in the lab when I was considering how to respond to this issue. Please don't make assumptions about things you don't know about. In addition I am not "imposing my will" on staff members. I am not going to stop staff members from spongebobing text if they wish, though I may dislike it. The OCF wants to be a welcoming and inclusive organization, and including spongebob is detrimental to those goals. Therefore it is entirely in line with current culture and procedure to remove something that would conflict with our goals of inclusivity.

2) "This is completely imagined outrage." I linked various tweets demonstrating that people with disabilities were hurt by this meme and a blog post articulating the logic behind why it is so offensive. This isn't imagined. In addition, there is a [meme generator](https://imgflip.com/memegenerator/114862909/Spongebob-handicap) that literally says "Spongebob handicap meme generator" in its title.

3) "Its about a chicken and always has been." Though the original image is based on a spongebob episode where Spongebob acts like a chicken, I fail to see how the text has anything to do with chickens. Furthermore, if the meme was about chickens, why would the aforementioned meme generator titled "Spongebob handicap Meme Generator" exist? However you interpret it, it is used to mock people with disabilities, so I think on those grounds alone it should be removed.

4) You accuse me and others of dishonesty for holding our position, yet you support Jerry for making a completely disingenuous comment which is not only unreasonable, but also offensively mocking people with disabilities. I am shocked and dismayed by this behavior. As members of OCF staff you are expected to act with respect towards others. Both you and Jerry have shown disrespect for the people who I linked to, and to people with disabilities in general. I hope you both spend some time to reflect on what you have said and how it can make people feel.

5) You seem to be completely missing the argument. No one is saying the macro should go due to the way people use it in the OCF. I am saying that the macro text was designed to imitate people with speech disorders or other mental disabilities in an insulting way. I did not ask for proof that the meme wasn't ableist, I merely asked for evidence that would refute my points. I have yet to receive any.

Seeing as no one has been able to provide reasonable evidence refuting issues with the macro text, I am now going to merge this PR.

**Comment by dkess** [comment]
>I did not ask for proof that the meme wasn't ableist, I merely asked for evidence that would refute my points. I have yet to receive any.

I'm not going to spend more time arguing this, since it's you call-- but what exactly was the kind of evidence you were looking for? Your original points were about ableism.

**Comment by yvbbrjdr** [comment]
Goodbye, OCF, for the next semester.

**Pull request merged**
