### PR TITLE
plugin: automatically spongebob memes

### PR DESCRIPTION
**Pull request by keur**

### CODE REVIEW

**Comment by dkess** [comment]
We should be careful with having the bot talk when it's not explicitly called on, but I'd be willing to try this out. If it gets annoying I'll revert it though.

**Comment by fydai** [comment]
I would add Donald J. Trump (so his tweets gets spongebob'd (assuming create is allowed to respond to itself)).

**Comment by keur** [comment]
@fydai Unfortunately, `create` can't respond to itself at the moment. Nothing would stop it from responding to the spongebob'd version, ad infinitum. I added the 'J' anyway.

**Comment by fydai** [comment]
Maybe anything containing https://twitter.com/realDonaldTrump should be spongbob'd rather than regularly printed instead?

**Pull request merged**
